export const EMPTY_SHOP_DETAILS='EMPTY_SHOP_DETAILS';
export const GET_SHOP_DETAILS='GET_SHOP_DETAILS';
export const GET_SHOPS='GET_SHOPS';
export const SHOP_REGISTRATION = 'SHOP_REGISTRATION';
export const SHOP_FLAG='SHOPS';
